language: java
jdk:
- oraclejdk8
after_success:
- "./gradlew build jacocoTestReport coveralls"
- "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$TRAVIS_BRANCH -Dsonar.github.oauth=$GITHUB_ACCESS_TOKEN"
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: david.ahern26@gmail.com
  password:
    secure: TYETV87aD0A3XQ1Zf2voFgK+NASSwN1kjzMjnNdkZ43PKxW3kx3glu7zPB8FnN++O2j84qF5keZdxT1uBJS7exyLIv79GbvtucZ7eJXzvVvahnumDDoL7UdcNv7CywLUHMIaNvHhioZ+AI8lneBSf5mR0N/9n7+vuZGmRzv2yGqAr0EwaCZF8xHxQrqX0Z5sf7WS8w4I1xjiJUDbbg+9H3msTSVBkRSUXK0jgpaT2igRoq7zlWUDduLkt3jyfEHqfUSmh85lSLrcpW6jFyGwHN7brFRxR8biAYmN833cpCQ7VpgQS4PwHaZs4L0YoLm2hToLa1Vt6db4PtM6w5km8hPU7f9ECpAQSk7nL3PWPf9Dj3KX08GvZrICcW+JJlIDMtk6Tr24uAL0IdffnLwEe3FLbYc47cRuN7rfC4uRqdEAnss2+KSPYIgHX8dVRhiUlYoURR0EeqfRkIkgbo+GgFPslL1u2oi24Bi8em5v04xv0HUgTR+qdjU7j0Z9DECbvWShHzaA8hnYoce03AoUs5riskMwQf+lRsTxcw8Nph2tL3aA7dWMG6TQpYFHKdbAGZPQdCQ4erICeP5RnQjDgSt1NA/zv/M/KN0MkRzXEXYfrC1MMJaGkqL94GwRmdlL5W8eeezXbtGSAt6qe5mgXUW3Z8+NJR7SKul72FEPJZg=
  organization: thor
  space: prod
  on:
    repo: CIT-Team-Bravo/cardsec
    branch: master
